"""Generate the intranet conda ``environment.yml`` from ``pyproject.toml``.

``pyproject.toml`` is the only place a dependency is declared. The extranet installs it with
``uv``; the intranet (no PyPI, conda only) gets this generated file. ``--check`` regenerates in
memory and fails if the committed file drifted, so the two environments cannot silently diverge.

Usage::

    python tools/gen_conda_env.py            # write environment.yml
    python tools/gen_conda_env.py --check    # exit 1 if environment.yml is stale
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

#: Extras installed on the intranet. ``kernels`` is built from source inside the env.
INTRANET_EXTRAS = ("dev", "hf", "viz", "bench", "ced", "pm", "kernels")

#: PyPI name -> conda-forge name where they differ.
CONDA_NAME = {
    "crucible-kernels": None,  # local source, installed by pip below
}

#: Build toolchain for kernels/ (capnp + zstd C++ libs, nanobind, compilers).
KERNEL_BUILD = [
    "cxx-compiler",
    "c-compiler",
    "cmake>=3.24",
    "ninja",
    "pkg-config",
    "capnproto>=1.0",
    "zstd",
    "nanobind>=2.4",
    "scikit-build-core>=0.10",
]

_REQ = re.compile(r"^\s*([A-Za-z0-9_.\-]+)\s*([^;]*?)\s*(?:;\s*(.*))?$")


def _parse(req: str) -> tuple[str, str, str]:
    m = _REQ.match(req)
    if m is None:
        raise ValueError(f"cannot parse requirement {req!r}")
    return m.group(1), m.group(2).replace(" ", ""), (m.group(3) or "").strip()


def _linux_ok(marker: str) -> bool:
    """Keep deps whose marker is true on the intranet's linux boxes."""
    if not marker:
        return True
    if "sys_platform == 'linux'" in marker or "sys_platform != 'win32'" in marker:
        return True
    if "sys_platform == 'win32'" in marker:
        return False
    raise ValueError(f"unhandled environment marker {marker!r}; extend _linux_ok")


def render() -> str:
    """Render environment.yml for :data:`INTRANET_EXTRAS`."""
    py = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    reqs = list(py["dependencies"])
    for extra in INTRANET_EXTRAS:
        reqs.extend(py["optional-dependencies"][extra])
    pyver = py["requires-python"].removeprefix(">=")
    conda: dict[str, str] = {}
    for r in reqs:
        name, spec, marker = _parse(r)
        if not _linux_ok(marker):
            continue
        cname = CONDA_NAME.get(name, name)
        if cname is None:
            continue
        conda[cname.lower()] = spec
    lines = [
        "# GENERATED by tools/gen_conda_env.py from pyproject.toml -- do not edit by hand.",
        f"# extras: {', '.join(INTRANET_EXTRAS)}",
        "name: crucible",
        "channels:",
        "  - conda-forge",
        "dependencies:",
        f"  - python>={pyver},<3.15",
        *[f"  - {n}{s}" for n, s in sorted(conda.items())],
        *[f"  - {b}" for b in KERNEL_BUILD],
        "  - pip",
        "  - pip:",
        "    - --no-build-isolation",
        "    - -e .",
        "    - ./kernels",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    dst = REPO / "environment.yml"
    if a.check:
        if not dst.exists() or dst.read_text(encoding="utf-8") != text:
            print("environment.yml is stale: run python tools/gen_conda_env.py", file=sys.stderr)
            raise SystemExit(1)
        print("environment.yml up to date")
        return
    dst.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
